name: WotlweduIOS
options:
  bundleIdPrefix: com.wotlwedu
  deploymentTarget:
    iOS: "16.0"
configs:
  Debug: debug
  Release: release
settings:
  base:
    SWIFT_VERSION: 5.9
    IPHONEOS_DEPLOYMENT_TARGET: 16.0
    TARGETED_DEVICE_FAMILY: "1,2"
    PRODUCT_BUNDLE_IDENTIFIER: com.wotlwedu.mobile
    INFOPLIST_FILE: WotlweduIOS/Resources/Info.plist
targets:
  WotlweduIOS:
    type: application
    platform: iOS
    sources:
      - path: WotlweduIOS
    resources:
      - path: WotlweduIOS/Resources
    settings:
      base:
        PRODUCT_NAME: Wotlwedu
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
